plugins {
    id 'fabric-loom' version '1.11-SNAPSHOT'
}

sourceCompatibility = JavaVersion.VERSION_17
targetCompatibility = JavaVersion.VERSION_17

archivesBaseName = 'welcomekitajima'
version = '2.8.1'
group = 'net.coutman.welcomekitajima'

loom {
    mixin {
        defaultRefmapName = actualmodid + ".refmap.json"
    }
}
repositories {
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        name = "Ladysnake Libs"
        url = 'https://maven.ladysnake.org/releases'
    }
    maven {
        url = "https://maven.shedaniel.me/"
    }
}



dependencies {
    minecraft "com.mojang:minecraft:1.20.1"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.fabric_loader_ver}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.92.6+1.20.1"
    include modImplementation (annotationProcessor("io.github.llamalad7:mixinextras-fabric:0.5.0"))

    // add support for seven elements and its requirements
    modImplementation "maven.modrinth:seven-elements:${project.seven_elements_version}"
    modRuntimeOnly "me.shedaniel.cloth:cloth-config-fabric:${project.cloth_config_ver}"
    modImplementation "dev.onyxstudios.cardinal-components-api:cardinal-components-base:${project.cca_version}"
    modImplementation "dev.onyxstudios.cardinal-components-api:cardinal-components-entity:${project.cca_version}"
    modImplementation "dev.onyxstudios.cardinal-components-api:cardinal-components-item:${project.cca_version}"

}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 17
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

jar {
    from "LICENSE"
}
